### ISSUE TITLE
Push Notification Custom Sound

### ISSUE THREAD

**Issue by Diego-Franco** [urbanairship/react-native-module#113]
Hi UATeam, I have a question about how can I setup a custom sound for push notification

> {n=79, 
com.urbanairship.push.PUSH_ID=abcdefgh, com.urbanairship.push.CANONICAL_PUSH_ID=123456789, 
url=app://deeplink, 
sound=notification.wav, 
com.urbanairship.push.APID=1234567890, 
from=09876543,
google.sent_time=1524705482606, 
i=13700,
t=DR, 
com.urbanairship.push.ALERT=This is a push notification message, 
r=notifications, 
google.message_id=1232312, 
google.ttl=2419200}

I'm getting this in the push notification object, after read all the classes you have, I know in the PushMessage class if the notification contains **com.urbanairship.sound** will be update the NotificationFactory. 

I tried to update manually the NotificationFactory doing this:

> Uri soundUri = Uri.parse(soundString);       
NotificationFactory notificationFactory = UAirship.shared().getPushManager().getNotificationFactory();
notificationFactory.setSound(soundUri);
UAirship.shared().getPushManager().setNotificationFactory(notificationFactory);

but doesn't works, so, with the previous information, the question is, if I change the variable **sound** to **com.urbanairship.sound** in my payload for push notification, the sound would change? 

I know the **.wav** file has to be in the Android app resource folder, if not can you help me with this?

**Comment by marc-scig** [comment]
Hi @Diego-Franco,

The default NotificationFactory will parse the sound on its own as long as you use the "com.urbanairship.sound" key, and the file name as the value in the push payload. The actual Uri is more complicated than just the name, because it's a full path to the resource. This usually looks something like "android.resource://PACKAGE_NAME/RESOURCE_ID". But you don't have to worry about that if you do it using the push message.

I should also add that if for Android O devices and newer, the old way of settings sounds a notification is no longer supported. Since Android O, you're supposed to use a NotificationCategory and return a sound from its getSound method:

https://developer.android.com/reference/android/app/NotificationChannel#getSound()
https://docs.urbanairship.com/platform/android/#notification-channels

**Comment by Diego-Franco** [comment]
Nice, thank you @marc-scig , so in this case, I have other question

I have my project like:

react-native-project
  -> node_modules -> urbanairship_module
  -> android
  -> iOS

my sound file has to be in the **android** and **iOS** folder correct? and then in the payload I have to change to **com.urbanairship.sound = sound.wav**

The app is only supporting android 5 and above, so I think will be fine with that

**Comment by marc-scig** [comment]
Yes that key value combination should work for android < API 26. And in fact, if you are using our push API you probably don't even need to use the extra directly, as there's a "sound" key in the REST API you can use for both platforms, in the platform override section:

https://docs.urbanairship.com/api/ua/#notification-payload-android
https://docs.urbanairship.com/api/ua/#notification-payload-ios

This is probably a better way to go about it, because the iOS SDK doesn't use "com.urbananairship.sound" as an extra.

I believe on android the sound should be in the resources folder, and on iOS it just needs to be added to the project so that it's part of the app bundle (the same way you'd add other resources like images).

**Comment by rlepinski** [comment]
@Diego-Franco take a look here - https://github.com/urbanairship/react-native-module/issues/63. I provide a code sample that shows how to set the sound for Android O.

Basically our sound per notification support is no longer feasible with Android O, and those APIs are effectively deprecated for Android O+. To support the wide range of devices, you still need to set the sound like you are doing, but you also need to supply a default channel for Android O support.

Ill create internal tickets to make sure its documented in our source code and docs, as well as create a ticket for Android Notification Channel support so you can define your channels through react.
