### ISSUE TITLE
Push Notification is not floating or playing a sound, only appears on message center

### ISSUE THREAD

**Issue by netgfx** [urbanairship/react-native-module#227]
# Preliminary Info

### What Airship dependencies are you using?
5.0.0

### What are the versions of any relevant development tools you are using?
React Native 0.60
Android 9.0

# Report

### What unexpected behavior are you seeing?
The received PN doesn't float or playing a sound, settings are also disabled for Floating and Sound

### What is the expected behavior?
It should by default function like any other PN

**Comment by BrianBatchelder** [comment]
Hello, @netgfx. Thank you for bringing this to our attention. I have a few questions for you:
- Are you creating custom notification channels as described in [our docs](https://docs.airship.com/platform/react-native/push-notifications/#adding-custom-notification-channels-android)? If so, please provide a copy of your `ua_custom_notification_channels.xml`.
- Could you please provide more description, and maybe a screenshot, for your statement: "settings are also disabled for Floating and Sound"?
- Have you tried this on other Android versions, e.g. Android 10.0? What were your results?

**Comment by netgfx** [comment]
Thanks for reaching out.
1) No not custom notifications, simple notification from the Airship dashboard
2) ![Screenshot_2019-11-11-22-29-26-905_com android settings](https://user-images.githubusercontent.com/864248/68618964-28f55a00-04d3-11ea-97d9-ed6b1bfc3c72.png)
3) I have tried with Android 6.1 and have the same results, not 10 though.

I should also note the device is a Xiaomi Redmi 5 and a Samsung J5

**Comment by BrianBatchelder** [comment]
@netgfx: Is that screenshot from Android 9? Our sample app's notification settings look quite different in Android 9 (albeit in the emulator):
![Screenshot_1573506045](https://user-images.githubusercontent.com/2123928/68620908-5aded000-0483-11ea-9d1d-cf27a6236f29.png)

**Comment by BrianBatchelder** [comment]
Our research shows that Xiaomi might be disabling the Floating and Sound settings due to the priority of our default notification channel. Using the instructions [here](https://docs.airship.com/platform/android/push-notifications/#notification-channels), can you try creating and using a higher-priority (higher importance) notification channel using [`NotificationChannel`](https://developer.android.com/reference/android/app/NotificationChannel) or [`NotificationChannelCompat`](https://docs.airship.com/reference/libraries/android/latest/reference/com/urbanairship/push/notifications/NotificationChannelCompat.html), and see if the settings become enabled?  You will need to remove and recreate any channels that already exist if you want to change their priority.

**Comment by netgfx** [comment]
It appears that indeed was a specific mobile device specific issue, when tried again on a release version I got both sound and popup PN to appear. Thanks for the help!
