### ISSUE TITLE
MessageView not scrollable

### ISSUE THREAD

**Issue by lukebars** [urbanairship/react-native-module#330]
# Preliminary Info

### What Airship dependencies are you using?

`package.json`:
```
    "urbanairship-react-native": "^11.0.1",
```

`Podfile.lock`:
```
     - urbanairship-react-native (11.0.1):
        - Airship (= 14.3.0)
        - React-Core
     - AirshipExtensions/NotificationService
```

### What are the versions of any relevant development tools you are using?

    "react-native": "0.63.3",
    "react": "16.13.1",
    "@react-navigation/bottom-tabs": "^5.11.10",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",

# Report

### What unexpected behavior are you seeing?
MessageView is not scrollable if content is longer than screen. Wrapping it with a scrollview doesn't help.

### What is the expected behavior?
MessageView should be scrollable if content is long enough.

### What are the steps to reproduce the unexpected behavior?
Send a long message to message center on example app.

**Comment by rlepinski** [comment]
Thanks for the report, we will take a look

**Comment by rlepinski** [comment]
We were able to reproduce this. Hopefully have a fix in the near future.

**Comment by rlepinski** [comment]
We were able to reproduce this. Hopefully have a fix in the near future.

**Comment by marc-scig** [comment]
@lukebars can you share the code you're using to render the message view? I was able to reproduce the issue using our react native sample app, but the problem is technically in the example itself, not in the module.

There's an activity indicator in our sample that displays on top of the message while the native webview is loading the URL, which you can see here https://github.com/urbanairship/react-native-module/blob/main/example/screens/MessageScreen.js#L86

It looks like this is intercepting all the touch events after loading finishes, preventing them from being passed on to the message view. An easy way to make the problem go away is to add a `pointerEvents=none` argument to the view containing the activity indicator, which disables touch for that component:

```
return (
  <View style={styles.backgroundContainer}>
    <MessageView messageId={messageId}
      onLoadStarted={this.startLoading}
      onLoadFinished={this.finishLoading}
      onLoadError={this.failedLoading}
      style={{ flex: 1 }}
    />
    <View pointerEvents="none" style={styles.loadingIndicator}>
      <ActivityIndicator size="large"
        animating={this.state.animating}
      />
    </View>
  </View>
);
```

Another way, and probably more correct, would be to completely remove that view from the layout when it's not being used:

```
return (
  <View style={styles.backgroundContainer}>
    <MessageView messageId={messageId}
      onLoadStarted={this.startLoading}
      onLoadFinished={this.finishLoading}
      onLoadError={this.failedLoading}
      style={{ flex: 1 }}
    />
    {this.state.animating && 
    <View style={styles.loadingIndicator}>
      <ActivityIndicator size="large"
        animating={this.state.animating}
      />
    </View>
    }
  </View>
);
```

Let us know if this helps, or if the problem you're seeing is of a different nature. We'll likely be updating the example code in the repo, but if it's an implementation issue there's no need to push out an update to the module on npm.

**Comment by lukebars** [comment]
@marc-scig @rlepinski Yep that was the case, we've used the given example code. Thanks :shipit:
