### ISSUE TITLE
Mesage Center Filtering

### ISSUE THREAD

**Issue by ahmedu007** [urbanairship/react-native-module#449]
❗For how-to inquiries involving Airship functionality or use cases, please
contact [support](https://support.airship.com/).

# Preliminary Info

### What Airship dependencies are you using?

"urbanairship-react-native": "14.3.1"

# Report

### What unexpected behavior are you seeing?
[iOS message center](https://docs.airship.com/platform/ios/message-center/#message-center-filtering) and [Android message center](https://docs.airship.com/platform/android/message-center/#message-center-filtering) both have an option to set Message filtering predicate. However, using React Native SDK I couldn't find an option to do that. I looked online for guides or any other API but wasn't successful. Is there something I'm missing? How do we achieve this with RN?

### What is the expected behavior?
Filter the message by setting a predicate

**Comment by rlepinski** [comment]
@ahmedu007 Your most flexible option is to define a message center directly in react-native so you have full control over the message list you are rendering. The OOTB UI Message predicates are defined programmatically in the native SDK. To make it possible to define it from react-native we would have to define a JSON object that could describe how to filter it. We actually already have a JSON predicate we could use for that, but the options to filter it are limited since its more or less static filtering. 

How are you looking to filter the message list?

**Comment by ahmedu007** [comment]
Hey @rlepinski 
Thanks for such a quick response. We've implemented a custom UI for the Message center already. Pressing on the message renders another custom view, which renders a `<MessageView />` component with some other styles on the page. 

What we want to achieve is, once the device has a `setNamedUser` called and a name attached, we want to only show the messages that the user is allowed to view. Rather than all the messages sent to device. More like an `Inbox` functionality, so if a user logs out and another user logs in, they can see different messages

**Comment by rlepinski** [comment]
@ahmedu007 What people usually do is add some ID as an extra on the message then you can filter the listing before you render it

**Comment by ahmedu007** [comment]
Ill give that a shot. Thanks @rlepinski
