### ISSUE TITLE
UrbanAirship.getNamedUser() returns null for configured Named User

### ISSUE THREAD

**Issue by IvaTsu** [urbanairship/react-native-module#456]
# Preliminary Info

### What Airship dependencies are you using?

"urbanairship-react-native": "^14.4.3"

### What are the versions of any relevant development tools you are using?

"react-native": "0.69.5"
"react": "18.2.0",

# Report

### What unexpected behavior are you seeing?

`UrbanAirship.getNamedUser()` returns `null` on Android and `undefined` on `iOS` for a project that works with Push Notifications (Notifications work already, so the channel and the Named User are set up).

I can call `UrbanAirship.getChannelId()` and get the channel, but when calling `UrbanAirship.getNamedUser() for a device that channel is already under Named User (I can see that at the Airship dash), the output is null.

Note: UrbanAirship.takeOff() happens before this call.

```
import { UrbanAirship } from 'urbanairship-react-native'
...
React.useEffect(() => {
  UrbanAirship.getChannelId().then((channel) => console.log({ channel }))
  UrbanAirship.getNamedUser().then((namedUser) => console.log({ namedUser }))
}, [])
```

### What is the expected behavior?

I expect to see the Named User identifier instead of null.

### Do you have logging for the issue?

Log of the above code execution:
```
 LOG  {"channel": "63ca56d2-1cc8-4c23-bbd6-2bdcaf07fb81"}
 LOG  {"namedUser": undefined}
 ```

**Comment by Ulrico972** [comment]
Hello,

I didn't notice any bug retrieving the named user on that version.
I believe the named user setting just didn't happen in your case.

Could you verify if the named user you set is retrievable from the Contact Management in the your dashboard project please ?

Otherwise, you could look for your channel id and see if the named user you set appears in the tag group `named_user_id` like on the following example:
<img width="1183" alt="Screen Shot 2022-09-29 at 4 43 19 PM" src="https://user-images.githubusercontent.com/24393953/193138986-0bc39b3c-81f5-4e59-93fb-344d1c6f61d6.png">

**Comment by IvaTsu** [comment]
Hello @Ulrico972,

Thanks for looking into that.

Please see the screenshot below, I feel like what you described above is valid so far.

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/7797773/193209043-7237844d-d3a1-4052-a4a7-4d989c8e6b4a.png">

**Comment by Ulrico972** [comment]
Hello @IvaTsu ,
Did you set the named user from the mobile SDK side ?
If not, I think that's why it's not working. For security reasons, the SDK can't fetch named users that has been set from server side.
So you'll have to set it from the mobile side.

**Comment by IvaTsu** [comment]
Hello @Ulrico972,

Thanks for the information.
The Named User is set from the back-end side. Then, it's understandable why it's getting `null`.
