### ISSUE TITLE
setAutoLaunchDefaultMessageCenter

### ISSUE THREAD

**Issue by digitalhobo** [urbanairship/react-native-module#64]
Hi Thanks for the great module.
When I set
UrbanAirship.setAutoLaunchDefaultMessageCenter(false)

and a push notification is received - it still opens the Message Center.

Tested on IOS 11 - iPhone7

**Comment by crow** [comment]
@digitalhobo Thanks for bringing this to our attention. Will get back to you when the issue is tracked down.

**Comment by mjordan-cp** [comment]
I ran into this same bug. The problem is in the file UARCTMessageCenter.m. Lines 29 and 35 check the UARCTAutoLaunchMessageCenterKey from standardUserDefaults using "objectForKey" instead of "boolForKey". Since the existence of the key is checked during airship launch and is created if it doesn't exist when it gets to the instances in UARCTMessageCenter.m the key exists and will always evaluate to true. The fix is to correctly use the boolForKey check in these instances.

**Comment by crow** [comment]
Just pushed a patch. The issue was as @mjordan-cp described above. Thanks again.

**Comment by digitalhobo** [comment]
Thanks 👍
