### ISSUE TITLE
Clarification: Channel ID in Android

### ISSUE THREAD

**Issue by idrakimuhamad** [urbanairship/react-native-module#80]
I implement urbanairship on my react native app. After user had logged in, inside the authentication saga, we called the below and listen to the registration event. 

```
UrbanAirship.setUserNotificationsEnabled(true)

UrbanAirship.addListener("register", (event) => {
  // save the channelId on the DB
});
```

On the iOS, I’ve observed that the channel ID always the same no matter how many time I’ve deleted the app and reinstalled it again. The only difference is between channel ID in development and production. 

However, on Android the channel ID for the same device keeps changing whenever we reinstall the app. Is this expected? If so, how do I maintain a correct device identifier so that I know that i want to only push to this particular device, not all of this unused ID. At the moment when we save channel ID we check if the channel ID already exists or not, so we only store a unique channel ID for the user. They might have multiple channel ID, which we assumed should represent multiple device.

Any thoughts in this?

**Comment by crow** [comment]
This is expected behavior on Android. On iOS, the SDK will attempt to retrieve the channel ID from the keychain if it's available. Reinstalling the app, or deleting data will result in a new channel ID being created upon fresh install. This represents the natural limit of channel IDs on the Android platform. [Named users](https://docs.urbanairship.com/api/ua/#api-named-users) will likely be of interest to you. These identifiers are meant to map to multiple channel IDs across devices.

**Comment by idrakimuhamad** [comment]
I see. That’s very helpful. Reading the docs left me confuse on what should I use and channel ID seems the straightforward way to do so. But thanks doe highlighting this to me. I’ll see on way to implement named users now.
